apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/instance: mean-demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: node
spec:
  selector:
    app: node
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
